// <auto-generated />
using Agendify.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Agendify.Migrations
{
    [DbContext(typeof(AgendifyDbContext))]
    partial class AgendifyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Agendify.Models.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Areas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Construcao"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Informatica"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Medico"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Beleza"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Educacao"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Transporte"
                        });
                });

            modelBuilder.Entity("Agendify.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Agendify.Models.Servico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AreaDeAtuacaoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Preco")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AreaDeAtuacaoId");

                    b.ToTable("Servicos");
                });

            modelBuilder.Entity("Agendify.Models.Servico", b =>
                {
                    b.HasOne("Agendify.Models.Area", "AreaDeAtuacao")
                        .WithMany("Servicos")
                        .HasForeignKey("AreaDeAtuacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AreaDeAtuacao");
                });

            modelBuilder.Entity("Agendify.Models.Area", b =>
                {
                    b.Navigation("Servicos");
                });
#pragma warning restore 612, 618
        }
    }
}
